// JavaScript Document
$('#sp-men').owlCarousel({
    loop:true,
    margin:15,
    nav:true,
	autoplay:true,
	dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})
$('#sp-women').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
	autoplay:true,
	dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})
$('#sp-kid').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
	autoplay:true,
	dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:3
        }
    }
})